include(GNUInstallDirs)
install(
  TARGETS ${CMAKE_PROJECT_NAME} ${CMAKE_PROJECT_NAME}_orgb
  EXPORT ${CMAKE_PROJECT_NAME}Library
  FILE_SET HEADERS)

if(UNIX)
  install(CODE "execute_process(COMMAND ldconfig)")
endif()

install(
  EXPORT ${CMAKE_PROJECT_NAME}Library
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/${CMAKE_PROJECT_NAME}/cmake
  NAMESPACE ${CMAKE_PROJECT_NAME}::)

install(FILES "${CMAKE_SOURCE_DIR}/cmake/${CMAKE_PROJECT_NAME}Config.cmake"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/${CMAKE_PROJECT_NAME}/cmake)

install(TARGETS ${CMAKE_PROJECT_NAME}_cli RUNTIME)
