name: build-windows
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, clang]
        include:
          - compiler: msvc
            preset: windows-msvc-debug-user-mode
          - compiler: clang
            preset: windows-clang-debug

    steps:
      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure CMake
        run: |
          cmake --preset ${{ matrix.preset }}
        env:
          VCPKG_ROOT: C:\vcpkg

      - name: Build
        run: |
          cmake --build build/${{ matrix.preset }}
