name: clang-format
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: '.'
          exclude: './third_party ./external'
          extensions: 'cppm,cxxm,ixx,mpp,cc,cxx,cpp,hh,hxx,hpp'
          clangFormatVersion: 18
          inplace: False
          style: file