name: cmake-format
on:
  pull_request_target:
    types: [opened]

jobs:
  cmake-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: neg-c/cmake-format-action@v0.1.3
        with:
          source: '.'
          exclude: 'third_party external'
          inplace: False
          style: file
